<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>RfidTestApp</AssemblyName>
    <RootNamespace>RfidTestApp</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CoreFramework_CS\CoreFrameworkMain.csproj" />
  </ItemGroup>
</Project>
